### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by luxmedia** [yireo/Yireo_CheckoutTester#13]
First many thanks for providing your extensions here!!

But i get an issue with magento 1.9.3.8 and CheckoutTester. The Shop uses stores, so the url looks like:
/de/checkouttester/index/success

but the page shows "Access denied", although i entered my static ip into the developers IP list. An order id is also set.
When i try to access the url without the store code, i am redirect to the 404 page.

Do i have to adapt the .htaccess in some way? Or do i have to Re-Index?

**Comment by luxmedia** [comment]
it works if i leave the IP setting empty, as you sayed.

**Comment by jissereitsma** [comment]
So I assume you are using a different IP then the one that is configured. Most likely because you are behind a proxy or something else. As of yet, I can't confirm any issue here, neither has this been reported by anyone else. I'll close this ticket now. Feel free to re-open. However, if you do, make sure to provide as much details as possible, because your issue seems related to your specific connection and is not something I can replicate with the details you have provided so far.
