### ISSUE TITLE
[Suggestion] PHP 7 Compatibility

### ISSUE THREAD

**Issue by fweb** [yireo/Yireo_CheckoutTester#7]
Hi - 

I'm unable to install the package via Magento Connect Downloader in CE 1.9.2.4 due to PHP 7. Requirements have PHP 7 listed here https://www.yireo.com/software/magento-extensions/checkout-tester

I tried adjusting package.xml for php max 7.0.5 but I received an error "CONNECT ERROR: Unsupported resource type"

Maybe I packed it incorrectly (7zip & Win 8), but just wanted to make you guys aware of this for future users.

Hope that helps for later...

**Comment by jissereitsma** [comment]
Thanks. MagentoConnect is considered by almost all Magento developers a bad thing to use, and indeed its settings are outdated. We will check upon this, but instead of fixing this and letting you then again use this outdated MagentoConnect thing, I recommend you to either download the source and upload it using git/SSH or use composer instead.

**Comment by fweb** [comment]
Yep we're doing that. Just wanted to provide the feedback :+1:

**Comment by jissereitsma** [comment]
We have now released version 0.1.9 for the sole purpose to support PHP 7 under MagentoConnect.
